stages:
  - build-manual
  - build

build-manual:
  stage: build-manual

  tags:
    - ubuntu-16.04

  artifacts:
    paths:
      - manual.pdf

  script: "tools/create-manual.sh"

build-linux-1404:
  stage: build

  tags:
    - ubuntu-14.04

  artifacts:
    paths:
      - voxie*.tar.gz

  script: "tools/create-release.sh"

  variables:
    VOXIEBUILD_PATH_HDF5: "/home/src/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared"
    # http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-patch1/bin/linux-centos7-x86_64-gcc485/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared.tar.gz
    VOXIEBUILD_URL_HDF5: "http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-patch1/src/hdf5-1.10.0-patch1.tar.bz2"

build-linux-1604:
  stage: build

  tags:
    - ubuntu-16.04

  artifacts:
    paths:
      - voxie*.tar.gz

  script: "tools/create-release.sh"

  variables:
    VOXIEBUILD_PATH_HDF5: "/home/src/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared"
    # http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-patch1/bin/linux-centos7-x86_64-gcc485/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared.tar.gz
    VOXIEBUILD_URL_HDF5: "http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-patch1/src/hdf5-1.10.0-patch1.tar.bz2"

build-windows:
  stage: build

  tags:
    - windows

  script: "powershell -ExecutionPolicy Unrestricted .\\tools\\build-windows.ps1"

  dependencies:
    - build-manual

  artifacts:
    paths:
      - voxie*.zip

  variables:
    VOXIEBUILD_PATH_VISUAL_STUDIO: "e:\\Microsoft Visual Studio 14.0"
    VOXIEBUILD_PATH_QT: "e:\\Qt\\Qt5.6.0\\5.6\\msvc2015_64"
    VOXIEBUILD_URL_QT_COPY: "https://www.ipvs.uni-stuttgart.de/files/pas/src/qt-everywhere-opensource-src-5.6.0.tar.gz"
    VOXIEBUILD_USE_GIT: "1"
    VOXIEBUILD_URL_BASE: "https://www.ipvs.uni-stuttgart.de/files/pas/src"
