stages:
  - build-manual
  - build

build-manual:
  stage: build-manual

  tags:
    - ubuntu-20.04

  artifacts:
    paths:
      - old-manual.pdf

  script: "tools/create-old-manual.sh"


check-formatting:
  stage: build

  tags:
    - ubuntu-20.04

  # Due to some gitlab / gitlab-runner bug (probably related to different versions) sometimes the end of the log will be cut off, avoid that by waiting at the end
  # https://forum.gitlab.com/t/this-job-does-not-have-a-trace/43597
  #script: "tools/check-formatting.py"
  script: "( trap 'echo Finishing...; sleep 3; echo Finished' EXIT && tools/check-formatting.py )"

build-linux-1604:
  stage: build

  tags:
    - ubuntu-16.04

  artifacts:
    paths:
      - voxie*.tar.gz

  # Due to some gitlab / gitlab-runner bug (probably related to different versions) sometimes the end of the log will be cut off, avoid that by waiting at the end
  # https://forum.gitlab.com/t/this-job-does-not-have-a-trace/43597
  #script: "tools/create-release.sh --unpack-meson --unpack-ninja --disable-help-browser"
  script: "( trap 'echo Finishing...; sleep 3; echo Finished' EXIT && tools/create-release.sh --unpack-meson --unpack-ninja --disable-help-browser )"

build-linux-1804:
  stage: build

  tags:
    - ubuntu-18.04

  # Due to some gitlab / gitlab-runner bug (probably related to different versions) sometimes the end of the log will be cut off, avoid that by waiting at the end
  # https://forum.gitlab.com/t/this-job-does-not-have-a-trace/43597
  #script: "tools/create-release.sh --unpack-meson"
  script: "( trap 'echo Finishing...; sleep 3; echo Finished' EXIT && tools/create-release.sh --unpack-meson )"

  artifacts:
    paths:
      - voxie*.tar.gz

build-linux-2004:
  stage: build

  tags:
    - ubuntu-20.04

  # Due to some gitlab / gitlab-runner bug (probably related to different versions) sometimes the end of the log will be cut off, avoid that by waiting at the end
  # https://forum.gitlab.com/t/this-job-does-not-have-a-trace/43597
  #script: "tools/create-release.sh"
  script: "( trap 'echo Finishing...; sleep 3; echo Finished' EXIT && tools/create-release.sh )"

  artifacts:
    paths:
      - voxie*.tar.gz
      - doc.tar.bz2

build-windows-10:
  stage: build

  tags:
    - windows-10

  script: "powershell -ExecutionPolicy Unrestricted .\\tools\\build-windows.ps1"

  dependencies:
    - build-manual

  artifacts:
    paths:
      - voxie*.zip

  variables:
    VOXIEBUILD_PATH_VISUAL_STUDIO_VC: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Auxiliary\\Build"
    VOXIEBUILD_PATH_QT: "c:\\Qt\\Qt5.6.3\\5.6.3\\msvc2015_64"
    VOXIEBUILD_URL_QT_COPY: "https://ipvs.informatik.uni-stuttgart.de/pas/src/qt-everywhere-opensource-src-5.6.3.tar.xz"
    VOXIEBUILD_USE_GIT: "1"
    VOXIEBUILD_URL_BASE: "https://ipvs.informatik.uni-stuttgart.de/pas/src"

build-macos:
  stage: build

  tags:
    - macosx

  script: 'PATH="/opt/Qt5.14.2/5.14.2/clang_64/bin:$PATH" QT_VERSION=5.14.2 tools/create-release-mac.sh --disable-hdf5 --disable-lapack'

  artifacts:
    paths:
      - voxie*.dmg

build-linux-2004-onlylib:
  stage: build

  tags:
    - ubuntu-20.04

  # Due to some gitlab / gitlab-runner bug (probably related to different versions) sometimes the end of the log will be cut off, avoid that by waiting at the end
  # https://forum.gitlab.com/t/this-job-does-not-have-a-trace/43597
  #script: "tools/build.sh --only-lib"
  script: "( trap 'echo Finishing...; sleep 3; echo Finished' EXIT && tools/build.sh --only-lib )"

build-linux-2004-nointern:
  stage: build

  tags:
    - ubuntu-20.04

  # Due to some gitlab / gitlab-runner bug (probably related to different versions) sometimes the end of the log will be cut off, avoid that by waiting at the end
  # https://forum.gitlab.com/t/this-job-does-not-have-a-trace/43597
  #script: "tools/create-release.sh --no-intern"
  script: "( trap 'echo Finishing...; sleep 3; echo Finished' EXIT && tools/create-release.sh --no-intern )"
